export type Unit = { name: string; semester?: 1 | 2 | 3 };

export const GRADE_ORDER = [
  "小1","小2","小3","小4","小5","小6",
  "中1","中2","中3",
  "高1","高2","高3",
];

export function getAdjacentGrades(grade: string): string[] {
  const idx = GRADE_ORDER.indexOf(grade);
  if (idx === -1) return [grade];
  const result: string[] = [];
  if (idx > 0) result.push(GRADE_ORDER[idx - 1]);
  result.push(grade);
  if (idx < GRADE_ORDER.length - 1) result.push(GRADE_ORDER[idx + 1]);
  return result;
}

// 数学/算数は同一テーブルで grade で引き分け
export const CURRICULUM: Record<string, Record<string, Unit[]>> = {
  算数: {
    小1: [
      { name: "数の概念（10までの数）" },
      { name: "たし算・ひき算（1桁）" },
      { name: "かたち（立体・平面）" },
      { name: "大きい数（100まで）" },
    ],
    小2: [
      { name: "大きい数（1000まで）" },
      { name: "たし算・ひき算（2桁）" },
      { name: "かけ算（九九）" },
      { name: "長さ・水のかさ" },
      { name: "三角形と四角形" },
    ],
    小3: [
      { name: "大きい数（万の位）" },
      { name: "わり算" },
      { name: "小数の基礎" },
      { name: "分数の基礎" },
      { name: "重さ" },
      { name: "円と球" },
      { name: "かけ算（2桁×1桁）" },
    ],
    小4: [
      { name: "大きな数（億・兆）" },
      { name: "折れ線グラフ" },
      { name: "角" },
      { name: "垂直と平行" },
      { name: "四角形（台形・平行四辺形・ひし形）" },
      { name: "分数（大小・同分母のたし引き）" },
      { name: "小数のたし算・ひき算" },
      { name: "面積（長方形・正方形）" },
      { name: "小数のかけ算・わり算" },
      { name: "変わり方調べ" },
    ],
    小5: [
      { name: "整数と小数（位の仕組み）" },
      { name: "体積" },
      { name: "小数のかけ算" },
      { name: "小数のわり算" },
      { name: "合同な図形" },
      { name: "図形の角（多角形の内角和）" },
      { name: "分数と小数（変換）" },
      { name: "分数のたし算・ひき算（異分母）" },
      { name: "平均" },
      { name: "単位量あたりの大きさ" },
      { name: "割合（百分率・歩合）" },
      { name: "帯グラフと円グラフ" },
      { name: "速さ" },
      { name: "正多角形と円周" },
      { name: "角柱と円柱" },
    ],
    小6: [
      { name: "文字と式" },
      { name: "分数のかけ算" },
      { name: "分数のわり算" },
      { name: "比とその利用" },
      { name: "図形の拡大と縮小" },
      { name: "対称な図形（線対称・点対称）" },
      { name: "円の面積" },
      { name: "角柱と円柱の体積" },
      { name: "比例と反比例" },
      { name: "場合の数（順列・組合せ入門）" },
      { name: "データの活用（度数分布・平均）" },
    ],
  },
  数学: {
    中1: [
      { name: "正の数・負の数", semester: 1 },
      { name: "文字と式", semester: 1 },
      { name: "方程式（一次方程式）", semester: 2 },
      { name: "比例と反比例", semester: 2 },
      { name: "平面図形（作図・移動）", semester: 1 },
      { name: "空間図形（立体・体積・表面積）", semester: 2 },
      { name: "データの分析（平均・中央値・最頻値）", semester: 3 },
    ],
    中2: [
      { name: "式の計算（単項式・多項式）", semester: 1 },
      { name: "連立方程式", semester: 1 },
      { name: "一次関数", semester: 2 },
      { name: "平行と合同（図形の性質）", semester: 2 },
      { name: "三角形と四角形の性質", semester: 3 },
      { name: "確率", semester: 3 },
      { name: "データの活用（箱ひげ図）", semester: 3 },
    ],
    中3: [
      { name: "多項式（展開・因数分解）", semester: 1 },
      { name: "平方根", semester: 1 },
      { name: "二次方程式", semester: 2 },
      { name: "関数y=ax²", semester: 2 },
      { name: "図形の相似", semester: 2 },
      { name: "円の性質", semester: 3 },
      { name: "三平方の定理", semester: 3 },
      { name: "標本調査", semester: 3 },
    ],
    高1: [
      { name: "数と式（整式・因数分解・実数）" },
      { name: "集合と論証" },
      { name: "二次関数" },
      { name: "図形と計量（三角比）" },
      { name: "データの分析（分散・標準偏差・相関）" },
      { name: "場合の数と確率" },
      { name: "図形の性質（平面図形・空間図形）" },
      { name: "整数の性質" },
    ],
    高2: [
      { name: "指数関数・対数関数" },
      { name: "三角関数" },
      { name: "数列（等差・等比・漸化式）" },
      { name: "ベクトル" },
      { name: "微分・積分（基礎）" },
    ],
  },
  国語: {
    小4: [
      { name: "物語文の読解" },
      { name: "説明文の読解" },
      { name: "詩" },
      { name: "漢字（4年配当160字）" },
      { name: "慣用句・ことわざ" },
      { name: "文の組み立て（主語・述語・修飾語）" },
    ],
    小5: [
      { name: "物語文・小説の読解" },
      { name: "説明文・論説文の読解" },
      { name: "随筆" },
      { name: "漢字（5年配当185字）" },
      { name: "敬語（尊敬語・謙譲語・丁寧語）" },
      { name: "熟語の構成" },
      { name: "詩・短歌" },
    ],
    小6: [
      { name: "物語文・小説の読解" },
      { name: "説明文・論説文の読解" },
      { name: "漢字（6年配当181字）" },
      { name: "四字熟語・熟語" },
      { name: "俳句・短歌" },
      { name: "古文入門（竹取物語・枕草子）" },
      { name: "語句の意味・文脈読解" },
    ],
    中1: [
      { name: "説明文・論説文", semester: 1 },
      { name: "物語・小説", semester: 2 },
      { name: "詩", semester: 1 },
      { name: "古文（竹取物語・今昔物語）", semester: 2 },
      { name: "漢文入門（書き下し・意味）", semester: 3 },
      { name: "漢字（中学基礎・入試頻出）" },
      { name: "文法（品詞・文節・係り受け）", semester: 1 },
    ],
    中2: [
      { name: "論説文・評論", semester: 1 },
      { name: "小説・随筆", semester: 2 },
      { name: "古文（枕草子・方丈記）", semester: 2 },
      { name: "漢文（故事成語・漢詩）", semester: 3 },
      { name: "漢字（中学標準）" },
      { name: "文法（用言の活用・助動詞）", semester: 1 },
    ],
    中3: [
      { name: "評論・論説文", semester: 1 },
      { name: "小説・詩歌", semester: 2 },
      { name: "古文（源氏物語・平家物語）", semester: 2 },
      { name: "漢文（史記・論語）", semester: 3 },
      { name: "漢字（入試頻出）" },
      { name: "文法（総合・古典文法）", semester: 1 },
    ],
    高1: [
      { name: "現代文（評論）" },
      { name: "現代文（小説）" },
      { name: "古文文法（動詞・形容詞の活用）" },
      { name: "古典文学（土佐日記・徒然草）" },
      { name: "漢文（訓読・句形）" },
    ],
  },
  英語: {
    小5: [
      { name: "アルファベット・フォニックス" },
      { name: "自己紹介（名前・年齢・好き嫌い）" },
      { name: "数・色・形・曜日・月" },
      { name: "身近な英単語" },
      { name: "簡単な質問と答え（What/Do you like）" },
    ],
    小6: [
      { name: "一般動詞（現在形）" },
      { name: "I can / I like / I want" },
      { name: "時間・場所・行事の表現" },
      { name: "英単語（小学必修600語）" },
      { name: "簡単な英文の読み書き" },
    ],
    中1: [
      { name: "be動詞（am/is/are）", semester: 1 },
      { name: "一般動詞（現在形）", semester: 1 },
      { name: "疑問文・否定文", semester: 1 },
      { name: "代名詞（I/my/me/mine）", semester: 1 },
      { name: "複数形・冠詞（a/an/the）", semester: 1 },
      { name: "形容詞・副詞", semester: 2 },
      { name: "疑問詞（what/who/where/when/why/how）", semester: 2 },
      { name: "命令文", semester: 2 },
      { name: "助動詞can", semester: 2 },
      { name: "現在進行形", semester: 2 },
      { name: "三人称単数現在（三単現のs）", semester: 2 },
      { name: "英単語（中1必修）" },
    ],
    中2: [
      { name: "過去形（規則動詞・不規則動詞）", semester: 1 },
      { name: "過去進行形", semester: 1 },
      { name: "未来形（will / be going to）", semester: 1 },
      { name: "接続詞（when/if/because/that）", semester: 2 },
      { name: "不定詞（名詞的・副詞的・形容詞的用法）", semester: 2 },
      { name: "動名詞", semester: 2 },
      { name: "比較（原級・比較級・最上級）", semester: 3 },
      { name: "受動態（受け身）", semester: 3 },
      { name: "英単語（中2必修）" },
    ],
    中3: [
      { name: "現在完了形（完了・経験・継続）", semester: 1 },
      { name: "分詞（現在分詞・過去分詞の形容詞的用法）", semester: 1 },
      { name: "関係代名詞（who/which/that）", semester: 2 },
      { name: "間接疑問文", semester: 2 },
      { name: "仮定法（if節）", semester: 3 },
      { name: "英単語（中3・入試頻出）" },
      { name: "英作文・英文読解", semester: 3 },
    ],
    高1: [
      { name: "時制（現在・過去・未来・完了形）" },
      { name: "助動詞（can/must/should/may/would）" },
      { name: "不定詞・動名詞（応用）" },
      { name: "分詞・分詞構文" },
      { name: "関係詞（関係代名詞・関係副詞）" },
      { name: "比較（応用・慣用表現）" },
      { name: "仮定法（過去・過去完了）" },
      { name: "英文読解（長文）" },
      { name: "英作文" },
    ],
  },
  理科: {
    小4: [
      { name: "季節と生き物" },
      { name: "天気と気温" },
      { name: "空気と水の性質" },
      { name: "月と星" },
      { name: "電流のはたらき" },
      { name: "物の体積と温度" },
      { name: "水のすがた変化（状態変化）" },
    ],
    小5: [
      { name: "植物の発芽・成長・結実" },
      { name: "メダカの誕生" },
      { name: "天気の変化" },
      { name: "流れる水のはたらき" },
      { name: "電磁石" },
      { name: "物のとけ方（溶解）" },
      { name: "ふりこの運動" },
    ],
    小6: [
      { name: "動物のからだのはたらき（消化・呼吸・循環）" },
      { name: "植物のからだのはたらき（光合成・蒸散）" },
      { name: "生物と環境（食物連鎖）" },
      { name: "てこのはたらき" },
      { name: "電気の利用（発電・蓄電）" },
      { name: "土地のつくりと変化（地層・火山・地震）" },
      { name: "月と太陽" },
    ],
    中1: [
      { name: "植物のからだと分類（花・葉・根・茎）", semester: 1 },
      { name: "動物の分類（脊椎・無脊椎）", semester: 2 },
      { name: "光・音・力のはたらき", semester: 1 },
      { name: "物質の性質（密度・金属・有機物・無機物）", semester: 1 },
      { name: "気体の性質（酸素・二酸化炭素・水素・アンモニア）", semester: 2 },
      { name: "水溶液（溶解度・質量パーセント濃度）", semester: 2 },
      { name: "状態変化（融点・沸点・蒸留）", semester: 2 },
      { name: "大地の変動（地層・岩石・火山・地震）", semester: 3 },
    ],
    中2: [
      { name: "細胞と組織（植物・動物）", semester: 1 },
      { name: "消化と吸収", semester: 1 },
      { name: "血液循環・呼吸・排出", semester: 2 },
      { name: "神経系・感覚器官", semester: 2 },
      { name: "化学変化（化合・分解・酸化・還元）", semester: 1 },
      { name: "化学変化と物質の質量（質量保存の法則）", semester: 2 },
      { name: "電流・電圧・抵抗（オームの法則）", semester: 2 },
      { name: "電流と磁界（モーター・発電機）", semester: 3 },
      { name: "気象（大気・前線・天気図）", semester: 3 },
    ],
    中3: [
      { name: "生殖（有性・無性）と遺伝（メンデルの法則）", semester: 1 },
      { name: "生物の進化", semester: 2 },
      { name: "イオンと電解質・電気分解", semester: 1 },
      { name: "酸・アルカリ・中和（pH）", semester: 2 },
      { name: "力のつりあいと運動（慣性・等速直線運動）", semester: 2 },
      { name: "仕事とエネルギー（力学的エネルギー保存）", semester: 2 },
      { name: "地球と宇宙（太陽系・星座・月の満ち欠け）", semester: 3 },
      { name: "自然環境と人間", semester: 3 },
    ],
    高1: [
      { name: "物理基礎（運動・力・エネルギー）" },
      { name: "化学基礎（物質の構成・化学結合）" },
      { name: "化学基礎（化学反応・酸塩基・酸化還元）" },
      { name: "生物基礎（細胞・代謝・遺伝情報）" },
      { name: "生物基礎（体内環境・生態系）" },
      { name: "地学基礎（固体地球・大気と海洋・宇宙）" },
    ],
  },
  社会: {
    小4: [
      { name: "都道府県・地域の様子" },
      { name: "飲料水・電気・ガスの仕組み" },
      { name: "ごみの処理と再利用" },
      { name: "自然災害と地域の安全" },
      { name: "郷土の伝統・文化・発展" },
    ],
    小5: [
      { name: "国土の地形と気候" },
      { name: "農業（米・野菜・果物・畜産）" },
      { name: "水産業（漁業・養殖）" },
      { name: "工業（自動車・食料品・製鉄）" },
      { name: "情報産業とメディア" },
      { name: "環境問題と国土の保全" },
    ],
    小6: [
      { name: "縄文・弥生・古墳時代" },
      { name: "飛鳥・奈良・平安時代" },
      { name: "鎌倉・室町時代" },
      { name: "安土桃山・江戸時代" },
      { name: "明治維新～大正時代" },
      { name: "昭和（戦争と現代）" },
      { name: "日本国憲法・三権分立" },
      { name: "国際社会と日本" },
    ],
    中1: [
      { name: "地理：地図・地形・気候の基礎", semester: 1 },
      { name: "地理：世界の地域（アジア・ヨーロッパ・アメリカなど）", semester: 1 },
      { name: "地理：日本の地域（地方別特色）", semester: 2 },
      { name: "歴史：古代文明（メソポタミア・エジプト・中国・ギリシャ）", semester: 1 },
      { name: "歴史：日本の古代（縄文～平安）", semester: 2 },
      { name: "歴史：中世（鎌倉・室町・戦国）", semester: 3 },
    ],
    中2: [
      { name: "歴史：近世（安土桃山・江戸幕府の政治）", semester: 1 },
      { name: "歴史：近代①（開国・明治維新・産業革命）", semester: 1 },
      { name: "歴史：近代②（大正デモクラシー・昭和前期・戦争）", semester: 2 },
      { name: "地理：日本の産業（農業・工業・貿易・運輸）", semester: 2 },
      { name: "地理：環境問題・資源エネルギー・人口", semester: 3 },
    ],
    中3: [
      { name: "歴史：現代（戦後復興・高度成長・現代）", semester: 1 },
      { name: "公民：日本国憲法・基本的人権", semester: 1 },
      { name: "公民：政治（国会・内閣・裁判所・地方自治）", semester: 2 },
      { name: "公民：経済（消費・生産・市場・企業）", semester: 2 },
      { name: "公民：財政・金融・社会保障", semester: 3 },
      { name: "公民：国際社会・持続可能な社会", semester: 3 },
    ],
    高1: [
      { name: "歴史総合（近代化・国際秩序の変化・グローバル化）" },
      { name: "地理総合（地図・環境・生活文化・防災）" },
      { name: "公共（個人・社会・倫理・政治・経済）" },
    ],
  },
};

// 算数・数学の隣接学年をまたぐ場合の科目解決
export function resolveSubject(subject: string, grade: string): string {
  if (subject === "数学" && grade.startsWith("小")) return "算数";
  if (subject === "算数" && !grade.startsWith("小")) return "数学";
  return subject;
}

export function getUnitsForGrade(subject: string, grade: string): Unit[] {
  const resolved = resolveSubject(subject, grade);
  return CURRICULUM[resolved]?.[grade] ?? [];
}

export const SUBJECT_LIST = ["国語", "算数", "数学", "英語", "理科", "社会"];
